apiVersion: v1
kind: Secret
metadata:
  name: neo4j-secret
type: Opaque
data:
  password: cGFzc3dvcmQ= # base64 encoded "password"
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  secret: eW91cl9qd3Rfc2VjcmV0X2tleV9oZXJlX211c3QiOiAiYWFhYWFhYWEiLCAic2lnbmF0dXJlIjogIjEifQ==